### ISSUE TITLE
www. prefix not working on web address

### ISSUE THREAD

**Issue by Lucase4c** [yeg-relief/issue-tracker#13]

**Comment by slmyers** [comment]
Will also cover links like http://youcanbenefit.ca/home not working with this issue.

**Comment by Lucase4c** [comment]
Cool, is there anything else we have talked about that we need to write down?

Maybe a “Make everything shiny” issue :D


Lucas Stone e4c
Financial Empowerment Coordinator

LStone@e4calberta.org<mailto:LStone@e4calberta.org>
T       780.424.5408 x163
C       780.554.0894

9321 Jasper Avenue, Edmonton AB T5H 3T7

e4calberta.org<https://e4calberta.org/>

[cid:MainLogo_55796721-010e-435f-9c40-0dc1a644656e.png]

This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient or the employee responsible for delivery of the message to the intended recipient, please be advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify us immediately by telephone and return the original email to us or destroy this message.

[cid:Environmentlogo_5cc24339-3bc0-40ee-87a1-6b0a51bb24dc.png]e4c supports environmental conservation - please print wisely.

**Comment by slmyers** [comment]
Not that I can recall. I think fixing the address issues, prettying up the user side and working on data migrations/backup is about all the time I can realistically afford.

**Comment by Lucase4c** [comment]
Would completely agree. I’ve just gotten behind on updating github and want to make sure everything is written down.


Lucas Stone e4c
Financial Empowerment Coordinator

LStone@e4calberta.org<mailto:LStone@e4calberta.org>
T       780.424.5408 x163
C       780.554.0894

9321 Jasper Avenue, Edmonton AB T5H 3T7

e4calberta.org<https://e4calberta.org/>

[cid:MainLogo_55796721-010e-435f-9c40-0dc1a644656e.png]

This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient or the employee responsible for delivery of the message to the intended recipient, please be advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify us immediately by telephone and return the original email to us or destroy this message.

[cid:Environmentlogo_5cc24339-3bc0-40ee-87a1-6b0a51bb24dc.png]e4c supports environmental conservation - please print wisely.

**Comment by slmyers** [comment]
`www.` prefix is working now. [deep linking](https://en.wikipedia.org/wiki/Deep_linking) doesn't break app with the exception of `/master-screener/results`. Will do redirection sometime soon-ish.

**Comment by slmyers** [comment]
redirection works `/master-screener/results` still a problem.

good: http://www.youcanbenefit.ca/master-screener/results/details/nvgrvJFOu9XRiHzpHVQpgqDEOB

~~bad: http://www.youcanbenefit.ca/master-screener/results~~

both requests deep link now yeah!
